package com.china.demo.example.domain.exception;

public enum ExceptionKey {
    AUTH_METHOD_NOT_SUPPORTED,
    ENTITY_CONFLICT,
    INTERNAL_SERVER_ERROR,
    INVALID_PROPERTY,
    INVALID_REQUEST,
    LABEL_NAME_HAS_EXIST,
    LABEL_SIZE_EMPTY,
    LABEL_SIZE_LIMIT,
    NO_ACCESS,
    NOT_AUTHORIZED,
    NOT_FOUND,
    RESOURCE_TYPE_NOT_MATCH,
    RESOURCE_VERSION_NOT_UNIQUE,
    SERVICE_UNAVAILABLE,
    NOT_CAPABLE_GENERATE_SECRET_KEY,
    MODIFY_APPLICATION_HAS_EXIST,
    INVALID_STATUS_TRANSITION,
    URL_EMPTY;
}
