CREATE TABLE example_resource (
  id VARCHAR(36) NOT NULL COMMENT '资源ID',
  name VARCHAR(100) NOT NULL COMMENT '资源名称',
  description VARCHAR(1000) NULL COMMENT '资源描述',
  created_by VARCHAR(64) COMMENT '创建人',
  updated_by VARCHAR(64) COMMENT '负责人',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
--   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
--   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
) DEFAULT CHARSET=utf8;
